site_name: VibeRL Documentation
site_description: A Reinforcement Learning framework built through vibe coding
site_url: https://0xwelt.github.io/VibeRL/
repo_url: https://github.com/0xWelt/VibeRL
repo_name: 0xWelt/VibeRL
site_author: 0xWelt

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/index.md
    - Agents:
      - Base Agent: api/agents/base.md
      - REINFORCE Agent: api/agents/reinforce.md
      - DQN Agent: api/agents/dqn.md
      - PPO Agent: api/agents/ppo.md
    - Networks:
      - Base Network: api/networks/base_network.md
      - Policy Network: api/networks/policy_network.md
      - Value Network: api/networks/value_network.md
    - Environments:
      - Snake Environment: api/envs/grid_world/snake_env.md
    - Utilities:
      - Common Utilities: api/utils/common.md
      - Training Utilities: api/utils/training.md
      - Mock Environment: api/utils/mock_env.md
      - Experiment Manager: api/utils/experiment_manager.md
    - Types: api/typing.md
    - CLI: api/cli.md

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            docstring_options:
              ignore_init_summary: false
            heading_level: 2
            inherited_members: false
            line_length: 100
            merge_init_into_class: true
            preload_modules: [pydantic, torch, gymnasium]
            relative_crossrefs: true
            separate_signature: true
            show_bases: true
            show_category_heading: false
            show_docstring_attributes: true
            show_docstring_description: true
            show_docstring_examples: true
            show_docstring_other_parameters: true
            show_docstring_parameters: true
            show_docstring_raises: true
            show_docstring_returns: true
            show_if_no_docstring: true
            show_inheritance_diagram: false
            show_labels: true
            show_root_full_path: false
            show_root_heading: true
            show_root_members_full_path: false
            show_signature: true
            show_signature_annotations: true
            show_source: true
            show_submodules: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0xWelt/VibeRL
  version:
    provider: mike

markdown_extensions:
  # 1️⃣ 先关掉默认的换行解析，防止 $$ 被拆段
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  # 2️⃣ 让 Markdown 保留 $ 和 $$ 原样输出
  - pymdownx.escapeall:
      hardbreak: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 0xWelt
